management:
  endpoints:
    jmx:
      exposure:
        include: \*
  endpoint:
    info:
      enabled: true

server:
  port: 8085
  error:
    whitelabel:
      enabled: false
spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: Spring boot, mvc, security, mirage, thymeleaf
  servlet:
    multipart.max-file-size: 1MB
  devtools:
    livereload:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  # SQL server
  datasource:
    # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # url: jdbc:sqlserver://localhost:1433;databaseName=BookDatabase
    # username: sqlserver
    # password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tiny.db.elephantsql.com:5432/efmygsrb
    username: efmygsrb
    password: q1EXqJFi2x6RJEcM1ab33aQVOBc_VNDv
    hikari:
      schema: public
logging:
  level:
    '[org.springframework]': ERROR
    # '[org.apache.logging.slf4j]': 
    
#   jpa:
#     hibernate:
#       ddl-auto: create
#     show-sql: true

# To initialize database, create table
